dependencies/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::prefix('admin')->group(function (){
    Auth::routes();

    Route::get('email', function (){
        return view('email');
    });

    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::get('calendar', 'CalendarController@index')->name('calendar');

    Route::resource('booking', 'BookingController');


    Route::get('rates/add/{id}', 'RatesController@create')->name('add_rates');
    Route::resource('rates', 'RatesController');

    Route::prefix('rooms')->group(function (){

        Route::get('room-types/create/picture', 'RoomTypePhotoController@index')->name('room_types_picture');
        Route::resource('room-types', 'RoomTypeController');
        Route::post('room-types/destroymany', 'RoomTypeController@destroyMany')->name('room_types_destroymany');

    });


    Route::get('rooms/add/{id}', 'RoomController@create')->name('add_room');
    Route::post('rooms/add/{id}', 'RoomController@store')->name('add_room_store');
    Route::resource('rooms', 'RoomController');

    Route::resource('payments', 'PaymentsController');

    Route::get('customers/search', 'CustomerController@search')->name('customers_search');
    Route:: resource('customers', 'CustomerController');
    Route::post('customers/destroymany', 'CustomerController@destroyMany')->name('customers_destroymany');

    Route::resource('pages', 'PagesController');


    Route::prefix('settings')->group(function (){
        Route::get('facilities/facility-type', 'FacilityController@setFacilityType')->name('facilities_typeset');
        Route::resource('facilities', 'FacilityController');
        Route::post('facilities/destroymany', 'FacilityController@destroyMany')->name('facilities_destroymany');

        Route::resource('facility-types', 'FacilityTypeController');
        Route::post('facility-types/destroymany', 'FacilityTypeController@destroyMany')->name('facility_types_destroymany');

        Route::resource('services', 'ServiceController');
        Route::post('services/destroymany', 'ServiceController@destroyMany')->name('services_destroymany');

        Route::post('policy/add-rule', 'PolicyController@saveRule')->name('partially_refund_rule');
        Route::resource('policy', 'PolicyController');
        Route::post('policy/destroymany', 'PolicyController@destroyMany')->name('policy_destroymany');
    });

    Route::prefix('system')->group(function (){
        Route::resource('users', 'UserController');
        Route::post('users/destroymany', 'UserController@destroyMany')->name('users_destroymany');

        Route::resource('roles', 'RoleController');
        Route::post('roles/destroymany', 'RoleController@destroyMany')->name('roles_destroymany');

        Route::resource('permissions', 'PermissionController');
        Route::post('permissions/destroymany', 'PermissionController@destroyMany')->name('permission_destroymany');

        Route::resource('statuses', 'StatusController');

        Route::resource('languages', 'LanguageController');
        Route::post('languages/destroymany', 'LanguageController@destroyMany')->name('language_destroymany');
        Route::get('languages/makedefault/{id}', 'LanguageController@makeDefault')->name('languages_makedefault');

    });



});

dependencies/app/Facility.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Facility extends Model
{
    protected $table = "facilities";
    protected $fillable = ['facility_type_id','status_id'];

    public function translate($local){
        return $this->hasMany('App\FacilityTranslation','facility_id')->where('local',$local)->first();
    }

    public function translateDefault(){
        $language = Language::where('default',1)->first();
        return $this->hasMany('App\FacilityTranslation','facility_id')->where('local',$language->abbreviation)->first();
    }

    public function translationSave(){
        return $this->hasMany('App\FacilityTranslation','facility_id');
    }


    public function facilityType(){
        return $this->belongsTo('App\FacilityType');
    }

    public function status(){
        return $this->belongsTo('App\DefaultStatus','status_id');
    }
}

dependencies/app/FacilityType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FacilityType extends Model
{
    protected $table = "facility_types";
    protected $fillable = [
        'name'
    ];
}

dependencies/app/Http/Controllers/FacilityController.php
<?php

namespace App\Http\Controllers;

use App\DefaultStatus;
use Illuminate\Http\Request;
use App\Facility;
use App\FacilityType;
use App\FacilityTranslation;
use App\Language;
use Validator;

class FacilityController extends Controller
{
    public function __construct() {
        $this->middleware(['auth', 'manageSetting']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $facilities = Facility::orderBy('id','desc')->paginate(10);
        $facility_types = FacilityType::all();
        return view('facilities.index')->with(['facilities'=>$facilities,'facility_types'=>$facility_types]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $languages = Language::orderBy('default','desc')->get();
        $facility_types = FacilityType::all();
        $status = DefaultStatus::all();
        return view('facilities.create')->with(['facility_types'=>$facility_types, 'languages'=>$languages,'status'=>$status]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $language = Language::all();
        $validate = ['facility_type'=>'required', 'status'=>'required'];
        foreach($language as $language){
            $validate['name'.$language->abbreviation] = 'required';

        }
        // validate the input
        $validation = Validator::make( $request->all(),$validate
        );

// redirect on validation error
        if ( $validation->fails() ) {
            // change below as required
            return \Redirect::back()->withInput()->withErrors( $validation->messages() );
        }
        else {
            $facility = new Facility();
            $facility->facility_type_id = $request->facility_type;
            $facility->status_id = $request->status;
            $facility->save();

            $translation = Facility::find($facility->id);
            $language = Language::all();
            foreach ($language as $language){
               $facility_translation = new FacilityTranslation(['local'=>'en','name'=>$request['name'.$language->abbreviation]]);
                $translation->translationSave()->save($facility_translation);
            }



            return redirect()->route('facilities.index')
                ->with('flash_message',
                    $facility->translateDefault()->name.' added.');




        }
      // return $validate;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('/admin/settings/facilities');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $languages = Language::orderBy('default','desc')->get();
        $facility_types = FacilityType::all();
        $facility = Facility::findOrFail($id);
        $status = DefaultStatus::all();
        return view('facilities.edit')->with(['facility_types'=>$facility_types, 'languages'=>$languages, 'facility'=>$facility,'statuses'=>$status]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $language = Language::all();
        $validate = ['facility_type'=>'required','status'=>'required'];
        foreach($language as $language){
            $validate['name'.$language->abbreviation] = 'required';

        }
        // validate the input
        $validation = Validator::make( $request->all(),$validate
        );

// redirect on validation error
        if ( $validation->fails() ) {
            // change below as required
            return \Redirect::back()->withInput()->withErrors( $validation->messages() );
        }
        else {
            $facility = Facility::findOrFail($id);
            $facility->facility_type_id = $request->facility_type;
            $facility->status_id = $request->status;
            $facility->save();

            $language = Language::all();
            foreach ($language as $language){
                $translation = FacilityTranslation::where('facility_id',$id)->where('local', $language->abbreviation)->first();
                $translation->name = $request['name'.$language->abbreviation];
                $translation->save();
            }

            return redirect('/admin/settings/facilities/'.$facility->id.'/edit')
                ->with('flash_message',
                    $facility->translateDefault()->name.' updated.');




        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $facility_translation = FacilityTranslation::where('facility_id',$id);
        $facility_translation->delete();
        $facility = Facility::findOrFail($id);
        $facility->delete();
        return redirect()->route('facilities.index')
            ->with(['flash_message'=>
                'Facility deleted.']);

    }

    public function destroyMany(Request $request){
        if ($request->multi_id != null){
            $facilities = Facility::findOrFail($request->multi_id);

            foreach ($facilities as $facility){
                $facility_translation = FacilityTranslation::where('facility_id',$facility->id);
                $facility_translation->delete();
                $facility->delete();


            }
            return redirect()->route('facilities.index')
                ->with(['flash_message'=>
                    'Facilities deleted.']);

        }
        else{
            return redirect()->route('facilities.index')
                ->with('warning',
                    'Please select at least one record.');

        }

    }

    public function setFacilityType(Request $request){
       if($request->facility_type != null){
            $facilities = Facility::where('facility_type_id',$request->facility_type)->orderBy('id','desc')->paginate(10);
            $facility_types = FacilityType::all();
            return view('facilities.index')->with(['facilities'=>$facilities,'facility_types'=>$facility_types, 'type'=>$request->facility_type]);

        }
        else{
            return redirect()->route('facilities.index');
        }
    }
}

dependencies/resources/views/facilities/create.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-white">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li class="active">
                        <a href="{{route('facilities.index')}}"><span class="title">Facilities</span></a>
                    </li>
                    <li>
                        <a href="{{route('facility-types.index')}}">Facility Types</a>
                    </li>
                    <li>
                        <a href="{{route('services.index')}}"><span class="title">Services</span></a>
                    </li>
                    <li>
                        <a href="{{route('policy.index')}}">Policy</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-white">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="/admin/dashboard">Home</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">Settings</a></li>
                <li class="breadcrumb-item"><a href="{{route('facilities.index')}}">Facilities</a></li>
                <li class="breadcrumb-item active">Add Facility</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>ADD FACILITY

                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <div class="card card-transparent">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-12">
                        @if(Session::has('flash_message'))
                            <div class="alert alert-success" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                {!! Session('flash_message') !!}
                            </div>

                        @endif

                                @if (sizeof($errors) != 0)
                                    <div class="alert alert-danger" role="alert">
                                        <button class="close" data-dismiss="alert"></button>
                                        @foreach($languages as $language)
                                            @if($errors->has('name'.$language->abbreviation)){{ $errors->first('name'.$language->abbreviation) }}<br>@endif
                                            @endforeach
                                        @if($errors->has('facility_type')){{ $errors->first('facility_type') }}<br>@endif

                                        @if($errors->has('status')){{ $errors->first('status') }}<br>@endif



                                    </div>


                           @endif
                        <p class="small hint-text">* Indicates a required field.</p>
                        <form id="form-work" class="form-horizontal" role="form" autocomplete="off" action="{{route('facilities.store')}}" method="post" novalidate="novalidate">
                            {{csrf_field()}}
                            <div class="form-group row{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">Name *</label>
                                <div class="col-md-9">
                                        <div class="card card-transparent">
                                            <!-- Nav tabs -->
                                            <ul class="nav nav-tabs nav-tabs-linetriangle hidden-sm-down" data-init-reponsive-tabs="dropdownfx">
                                                @foreach($languages as $language)
                                                    @if($language->default == 1)
                                                        <li class="nav-item">
                                                            <a href="#" class="active" data-toggle="tab" data-target="#{{$language->abbreviation}}" aria-expanded="true"><span>{{$language->name}}</span></a>
                                                        </li>
                                                        @else
                                                        <li class="nav-item">
                                                            <a href="#" data-toggle="tab" data-target="#{{$language->abbreviation}}" class="" aria-expanded="false"><span>{{$language->name}}</span></a>
                                                        </li>
                                                        @endif
                                                    @endforeach
                                            </ul>

                                            <!-- Tab panes -->
                                            <div class="tab-content">
                                                @foreach($languages as $language)
                                                    @if($language->default == 1)
                                                        <div class="tab-pane fade active show" id="{{$language->abbreviation}}" aria-expanded="true">
                                                            <input type="text" class="form-control error" id="name{{$language->abbreviation}}" placeholder="Fitness Center" name="name{{$language->abbreviation}}"  value="{{old('name'.$language->abbreviation)}}" required="" aria-required="true" aria-invalid="true">

                                                        </div>
                                                    @else
                                                        <div class="tab-pane" id="{{$language->abbreviation}}" aria-expanded="true">
                                                            <input type="text" class="form-control error" id="name{{$language->abbreviation}}" placeholder="Fitness Center" name="name{{$language->abbreviation}}"  value="{{old('name'.$language->abbreviation)}}" required="" aria-required="true" aria-invalid="true">

                                                        </div>
                                                    @endif
                                                @endforeach

                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <div class="form-group row{{ $errors->has('facility_type') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">Facility Type *</label>
                                <div class="col-md-9">
                                    @foreach($facility_types as $facility_type)
                                        @if(old('facility_type') == $facility_type->id)
                                            {{ Form::radio('facility_type',  $facility_type->id, true) }}
                                            {{ Form::label($facility_type->name, ucfirst($facility_type->name)) }}<br>
                                        @else
                                            {{ Form::radio('facility_type',  $facility_type->id ) }}
                                            {{ Form::label($facility_type->name, ucfirst($facility_type->name)) }}<br>
                                        @endif
                                    @endforeach
                                </div>
                            </div>
                            <div class="form-group row{{ $errors->has('status') ? ' has-error' : '' }}">
                                <label for="status" class="col-md-3 control-label">Status *</label>
                                <div class="col-md-9">
                                    @foreach($status as $status)
                                        @if(old('status') == $status->id)
                                            {{ Form::radio('status',  $status->id, true) }}
                                            {{ Form::label($status->name, ucfirst($status->name)) }}<br>
                                        @else
                                            {{ Form::radio('status',  $status->id ) }}
                                            {{ Form::label($status->name, ucfirst($status->name)) }}<br>
                                        @endif
                                    @endforeach
                                </div>
                            </div>


                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-3">
                                </div>
                                <div class="col-md-9">
                                    <a href="{{route('facilities.index')}}" class="btn btn-hotel btn-primary-hotel">Back</a>
                                    <button class="btn btn-hotel btn-sec-hotel" type="submit">Add</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>



        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
@endsection

dependencies/resources/views/facilities/edit.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-white">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li class="active">
                        <a href="{{route('facilities.index')}}"><span class="title">Facilities</span></a>
                    </li>
                    <li>
                        <a href="{{route('facility-types.index')}}">Facility Types</a>
                    </li>
                    <li>
                        <a href="{{route('services.index')}}"><span class="title">Services</span></a>
                    </li>
                    <li>
                        <a href="{{route('policy.index')}}">Policy</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-white">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="/admin/dashboard">Home</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">Settings</a></li>
                <li class="breadcrumb-item"><a href="{{route('facilities.index')}}">Facilities</a></li>
                <li class="breadcrumb-item active">Edit {{$facility->translateDefault()->name}}</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>EDIT {{$facility->translateDefault()->name}}

                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <div class="card card-transparent">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-12">
                        @if(Session::has('flash_message'))
                            <div class="alert alert-success" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                {!! Session('flash_message') !!}
                            </div>

                        @endif

                        @if (sizeof($errors) != 0)
                            <div class="alert alert-danger" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                @foreach($languages as $language)
                                    @if($errors->has('name'.$language->abbreviation)){{ $errors->first('name'.$language->abbreviation) }}<br>@endif
                                @endforeach
                                @if($errors->has('facility_type')){{ $errors->first('facility_type') }}<br>@endif



                            </div>


                        @endif
                        <p class="small hint-text">* Indicates a required field.</p>
                            <form method="POST" action="{{route('facilities.update',$facility->id)}}" accept-charset="UTF-8" id="form-work" class="form-horizontal" role="form" autocomplete="off" novalidate="novalidate">
                                <input name="_method" type="hidden" value="PUT">
                                <input name="_token" type="hidden" value="{{csrf_token()}}">
                                <div class="form-group row{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">Name *</label>
                                <div class="col-md-9">
                                    <div class="card card-transparent">
                                        <!-- Nav tabs -->
                                        <ul class="nav nav-tabs nav-tabs-linetriangle hidden-sm-down" data-init-reponsive-tabs="dropdownfx">
                                            @foreach($languages as $language)
                                                @if($language->default == 1)
                                                    <li class="nav-item">
                                                        <a href="#" class="active" data-toggle="tab" data-target="#{{$language->abbreviation}}" aria-expanded="true"><span>{{$language->name}}</span></a>
                                                    </li>
                                                @else
                                                    <li class="nav-item">
                                                        <a href="#" data-toggle="tab" data-target="#{{$language->abbreviation}}" class="" aria-expanded="false"><span>{{$language->name}}</span></a>
                                                    </li>
                                                @endif
                                            @endforeach
                                        </ul>

                                        <!-- Tab panes -->
                                        <div class="tab-content">
                                            @foreach($languages as $language)
                                                @if($language->default == 1)
                                                    <div class="tab-pane fade active show" id="{{$language->abbreviation}}" aria-expanded="true">
                                                        <input type="text" class="form-control error" id="name{{$language->abbreviation}}" placeholder="Fitness Center" name="name{{$language->abbreviation}}"  value="{{old('name'.$language->abbreviation,$facility->translate($language->abbreviation)->name)}}" required="" aria-required="true" aria-invalid="true">

                                                    </div>
                                                @else
                                                    <div class="tab-pane" id="{{$language->abbreviation}}" aria-expanded="true">
                                                        <input type="text" class="form-control error" id="name{{$language->abbreviation}}" placeholder="Fitness Center" name="name{{$language->abbreviation}}"  value="{{old('name'.$language->abbreviation,$facility->translate($language->abbreviation)->name)}}" required="" aria-required="true" aria-invalid="true">

                                                    </div>
                                                @endif
                                            @endforeach

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row{{ $errors->has('facility_types') ? ' has-error' : '' }}">
                                <label for="facility_type" class="col-md-3 control-label">Facility Type *</label>
                                <div class="col-md-9">
                                    @foreach($facility_types as $facility_type)
                                        @if($facility->facility_type_id == $facility_type->id)
                                            {{ Form::radio('facility_type',  $facility_type->id, true) }}
                                            {{ Form::label($facility_type->name, ucfirst($facility_type->name)) }}<br>
                                        @else
                                            {{ Form::radio('facility_type',  $facility_type->id ) }}
                                            {{ Form::label($facility_type->name, ucfirst($facility_type->name)) }}<br>
                                        @endif
                                    @endforeach
                                </div>
                            </div>
                            <div class="form-group row{{ $errors->has('status') ? ' has-error' : '' }}">
                                <label for="staus" class="col-md-3 control-label">Status *</label>
                                <div class="col-md-9">
                                    @foreach($statuses as $status)
                                        @if($facility->status_id == $status->id)
                                            {{ Form::radio('status',  $status->id, true) }}
                                            {{ Form::label($status->name, ucfirst($status->name)) }}<br>
                                        @else
                                            {{ Form::radio('$status',  $status->id ) }}
                                            {{ Form::label($status->name, ucfirst($status->name)) }}<br>
                                        @endif
                                    @endforeach
                                </div>
                            </div>






                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-3">
                                </div>
                                <div class="col-md-9">
                                    <a href="{{route('facilities.index')}}" class="btn btn-hotel btn-primary-hotel">Back</a>
                                    <button class="btn btn-hotel btn-sec-hotel" type="submit">Save Changes</button>
                                </div>
                            </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>



        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
@endsection