dependencies/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::prefix('admin')->group(function (){
    Auth::routes();

    Route::get('email', function (){
        return view('email');
    });

    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::get('calendar', 'CalendarController@index')->name('calendar');

    Route::resource('booking', 'BookingController');


    Route::get('rates/add/{id}', 'RatesController@create')->name('add_rates');
    Route::resource('rates', 'RatesController');

    Route::prefix('rooms')->group(function (){

        Route::get('room-types/create/picture', 'RoomTypePhotoController@index')->name('room_types_picture');
        Route::resource('room-types', 'RoomTypeController');
        Route::post('room-types/destroymany', 'RoomTypeController@destroyMany')->name('room_types_destroymany');

    });


    Route::get('rooms/add/{id}', 'RoomController@create')->name('add_room');
    Route::post('rooms/add/{id}', 'RoomController@store')->name('add_room_store');
    Route::resource('rooms', 'RoomController');

    Route::resource('payments', 'PaymentsController');

    Route::get('customers/search', 'CustomerController@search')->name('customers_search');
    Route:: resource('customers', 'CustomerController');
    Route::post('customers/destroymany', 'CustomerController@destroyMany')->name('customers_destroymany');

    Route::resource('pages', 'PagesController');


    Route::prefix('settings')->group(function (){
        Route::get('facilities/facility-type', 'FacilityController@setFacilityType')->name('facilities_typeset');
        Route::resource('facilities', 'FacilityController');
        Route::post('facilities/destroymany', 'FacilityController@destroyMany')->name('facilities_destroymany');

        Route::resource('facility-types', 'FacilityTypeController');
        Route::post('facility-types/destroymany', 'FacilityTypeController@destroyMany')->name('facility_types_destroymany');

        Route::resource('services', 'ServiceController');
        Route::post('services/destroymany', 'ServiceController@destroyMany')->name('services_destroymany');

        Route::post('policy/add-rule', 'PolicyController@saveRule')->name('partially_refund_rule');
        Route::resource('policy', 'PolicyController');
        Route::post('policy/destroymany', 'PolicyController@destroyMany')->name('policy_destroymany');
    });

    Route::prefix('system')->group(function (){
        Route::resource('users', 'UserController');
        Route::post('users/destroymany', 'UserController@destroyMany')->name('users_destroymany');

        Route::resource('roles', 'RoleController');
        Route::post('roles/destroymany', 'RoleController@destroyMany')->name('roles_destroymany');

        Route::resource('permissions', 'PermissionController');
        Route::post('permissions/destroymany', 'PermissionController@destroyMany')->name('permission_destroymany');

        Route::resource('statuses', 'StatusController');

        Route::resource('languages', 'LanguageController');
        Route::post('languages/destroymany', 'LanguageController@destroyMany')->name('language_destroymany');
        Route::get('languages/makedefault/{id}', 'LanguageController@makeDefault')->name('languages_makedefault');

    });



});

dependencies/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
    <script src="https://use.fontawesome.com/9712be8772.js"></script>
    @yield('top-scripts')

</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Hotel System') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    @if (!Auth::guest())
                    <li><a href="{{ route('dashboard') }}">Dashboard</a></li>
                    <li><a href="{{ route('calendar') }}">Calendar</a></li>
                    @can('Booking')
                        <li><a href="{{ route('booking.index') }}">Booking</a></li>
                    @endcan
                    @can('Rates')
                        <li><a href="{{ route('rates.index') }}">Rates</a></li>
                    @endcan
                    @can('Rooms')
                        <li><a href="{{ route('rooms.index') }}">Rooms</a></li>
                    @endcan
                    @can('Payments')
                        <li><a href="{{ route('payments.index') }}">Payments</a></li>
                    @endcan
                    @can('Customer')
                        <li><a href="{{ route('customer.index') }}">Customer</a></li>
                    @endcan
                    @can('Pages')
                        <li><a href="{{ route('pages.index') }}">Pages</a></li>
                    @endcan
                    @can('Setting')
                        <li><a href="#">Setting</a></li>
                    @endcan
                    @can('System')
                        <li><a href="{{route('permissions.index')}}">System</a></li>
                    @endcan
                    @endif
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>


                        </li>
                        <li>
                            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                Logout
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @if(Session::has('flash_message'))
        <div class="container">
            <div class="alert alert-success"><em> {!! session('flash_message') !!}</em>
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            @include ('errors.list') {{-- Including error file --}}
        </div>
    </div>

    @yield('content')
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<!-- jQuery CDN -->
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<!-- Bootstrap Js CDN -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- Custom Scroller Js CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
@yield('bottom-scripts')
</body>
</html>

dependencies/resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title>Hotel Booking System - by Degito</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no" />
    <link rel="apple-touch-icon" href="{{asset('/admin-assets/pages/ico/60.png')}}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{asset('/admin-assets/pages/ico/76.png')}}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{asset('/admin-assets/pages/ico/120.png')}}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{asset('/admin-assets/pages/ico/152.png')}}">
    <link rel="icon" type="image/x-icon" href="{{asset('favicon.ico')}}" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="Library of Hotel Booking System developed by Degito team" name="description" />
    <meta content="Blossom Kerr @bblxssom on Github" name="author" />
    <link href="{{asset('/admin-assets/assets/plugins/pace/pace-theme-flash.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('/admin-assets/assets/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('/admin-assets/assets/plugins/font-awesome/css/font-awesome.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('/admin-assets/assets/plugins/jquery-scrollbar/jquery.scrollbar.css')}}" rel="stylesheet" type="text/css" media="screen" />
    <link href="{{asset('/admin-assets/assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css" media="screen" />
    <link href="{{asset('/admin-assets/assets/plugins/switchery/css/switchery.min.css')}}" rel="stylesheet" type="text/css" media="screen" />
    <link href="{{asset('/admin-assets/pages/css/pages-icons.css')}}" rel="stylesheet" type="text/css">
    <link class="main-stylesheet" href="{{asset('/admin-assets/pages/css/themes/modern.css')}}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{asset('/admin-assets/css/custom-login.css')}}">
    <script type="text/javascript">
        window.onload = function()
        {
            // fix for windows 8
            if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
                document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="/admin-assets/pages/css/windows.chrome.fix.css" />'
        }
    </script>
</head>
<body class="fixed-header ">
<div class="login-wrapper ">
    <!-- START Login Background Pic Wrapper-->
    <div class="bg-pic">
        <!-- START Background Pic-->
        <img src="{{asset('/admin-assets/images/background.jpg')}}" data-src="{{asset('/admin-assets/images/background.jpg')}}" data-src-retina="{{asset('/admin-assets/images/background.jpg')}}" alt="Hotel" class="lazy">
        <!-- END Background Pic-->
        <!-- START Background Caption-->
        <div class="bg-caption pull-bottom sm-pull-bottom text-white p-l-20 m-b-20">
            <h2 class="semi-bold text-white" style="display: none">
                Pages make it easy to enjoy what matters the most in the life</h2>
            <p class="small" style="display: none">
                © 2017 Miratara CO.,LTD. All right reserved. Degihned and developed by <a href="https://www.degitobangkok.com">DEGITO</a></p>
        </div>
        <!-- END Background Caption-->
    </div>
    <!-- END Login Background Pic Wrapper-->
    <!-- START Login Right Container-->
    @yield('right-container')
    <!-- END Login Right Container-->
</div>

<!-- BEGIN VENDOR JS -->
<script src="{{asset('/admin-assets/assets/plugins/pace/pace.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/jquery/jquery-1.11.1.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/modernizr.custom.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/jquery-ui/jquery-ui.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/tether/js/tether.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/jquery/jquery-easy.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/jquery-unveil/jquery.unveil.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/jquery-ios-list/jquery.ioslist.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/jquery-actual/jquery.actual.min.js')}}"></script>
<script src="{{asset('/admin-assets/assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/admin-assets/assets/plugins/select2/js/select2.full.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/admin-assets/assets/plugins/classie/classie.js')}}"></script>
<script src="{{asset('/admin-assets/assets/plugins/switchery/js/switchery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/admin-assets/assets/plugins/jquery-validation/js/jquery.validate.min.js')}}" type="text/javascript"></script>
<!-- END VENDOR JS -->
<script src="{{asset('/admin-assets/pages/js/pages.min.js')}}"></script>

</body>
</html>