dependencies/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::prefix('admin')->group(function (){
    Auth::routes();

    Route::get('email', function (){
        return view('email');
    });

    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::get('calendar', 'CalendarController@index')->name('calendar');

    Route::resource('booking', 'BookingController');


    Route::get('rates/add/{id}', 'RatesController@create')->name('add_rates');
    Route::resource('rates', 'RatesController');

    Route::prefix('rooms')->group(function (){

        Route::get('room-types/create/picture', 'RoomTypePhotoController@index')->name('room_types_picture');
        Route::resource('room-types', 'RoomTypeController');
        Route::post('room-types/destroymany', 'RoomTypeController@destroyMany')->name('room_types_destroymany');

    });


    Route::get('rooms/add/{id}', 'RoomController@create')->name('add_room');
    Route::post('rooms/add/{id}', 'RoomController@store')->name('add_room_store');
    Route::resource('rooms', 'RoomController');

    Route::resource('payments', 'PaymentsController');

    Route::get('customers/search', 'CustomerController@search')->name('customers_search');
    Route:: resource('customers', 'CustomerController');
    Route::post('customers/destroymany', 'CustomerController@destroyMany')->name('customers_destroymany');

    Route::resource('pages', 'PagesController');


    Route::prefix('settings')->group(function (){
        Route::get('facilities/facility-type', 'FacilityController@setFacilityType')->name('facilities_typeset');
        Route::resource('facilities', 'FacilityController');
        Route::post('facilities/destroymany', 'FacilityController@destroyMany')->name('facilities_destroymany');

        Route::resource('facility-types', 'FacilityTypeController');
        Route::post('facility-types/destroymany', 'FacilityTypeController@destroyMany')->name('facility_types_destroymany');

        Route::resource('services', 'ServiceController');
        Route::post('services/destroymany', 'ServiceController@destroyMany')->name('services_destroymany');

        Route::post('policy/add-rule', 'PolicyController@saveRule')->name('partially_refund_rule');
        Route::resource('policy', 'PolicyController');
        Route::post('policy/destroymany', 'PolicyController@destroyMany')->name('policy_destroymany');
    });

    Route::prefix('system')->group(function (){
        Route::resource('users', 'UserController');
        Route::post('users/destroymany', 'UserController@destroyMany')->name('users_destroymany');

        Route::resource('roles', 'RoleController');
        Route::post('roles/destroymany', 'RoleController@destroyMany')->name('roles_destroymany');

        Route::resource('permissions', 'PermissionController');
        Route::post('permissions/destroymany', 'PermissionController@destroyMany')->name('permission_destroymany');

        Route::resource('statuses', 'StatusController');

        Route::resource('languages', 'LanguageController');
        Route::post('languages/destroymany', 'LanguageController@destroyMany')->name('language_destroymany');
        Route::get('languages/makedefault/{id}', 'LanguageController@makeDefault')->name('languages_makedefault');

    });



});

dependencies/app/Http/Controllers/FacilityTypeController.php
<?php

namespace App\Http\Controllers;

use App\Facility;
use Illuminate\Http\Request;
use App\FacilityType;
use Validator;

class FacilityTypeController extends Controller
{
    public function __construct() {
        $this->middleware(['auth', 'manageSetting']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $facility_type = FacilityType::orderBy('id', 'desc')->paginate(10);
        return view('facility_types.index')->with('facility_types', $facility_type);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('facility_types.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate the input
        $validation = Validator::make( $request->all(), [
            'name'=>'required|unique:facility_types',

        ]);

// redirect on validation error
        if ( $validation->fails() ) {
            // change below as required
            return \Redirect::back()->withInput()->withErrors( $validation->messages() );
        }
        else {
            $facility_type = new FacilityType();
            $input = $request->all();
            $facility_type->fill($input)->save();


            return redirect()->route('facility-types.index')
                ->with('flash_message',
                    $facility_type->name.' added.');


        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('/admin/settings/facility-types');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $facility_type = FacilityType::findOrFail($id);
        return view('facility_types.edit')->with('facility_type', $facility_type);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validate the input
        $validation = Validator::make( $request->all(), [
            'name'=>'required|unique:facility_types,name,'.$id,

        ]);

// redirect on validation error
        if ( $validation->fails() ) {
            // change below as required
            return \Redirect::back()->withInput()->withErrors( $validation->messages() );
        }
        else {
            $facility_type = FacilityType::findOrFail($id);
            $input = $request->all();
            $facility_type->fill($input)->save();

            return redirect('/admin/settings/facility-types/'.$facility_type->id.'/edit')
                ->with('flash_message',
                    $facility_type->name.' updated.');


        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $facility_type = FacilityType::findOrFail($id);
        $facility = Facility::where('facility_type_id', $facility_type->id)->get();

        //Make it impossible to delete this specific permission
       if (sizeof($facility) != 0) {
            return redirect()->route('facility-types.index')
                ->with('danger',
                    'Cannot delete this facility type.');
        }
        else{
           if($facility_type->id == 1 or $facility_type->id == 2){
               return redirect()->route('facility-types.index')
                   ->with('danger',
                       'Cannot delete this facility type because it a system default. But you can edit facility type name.');

           }
           else{
               $facility_type->delete();
               return redirect()->route('facility-types.index')
                   ->with('flash_message',
                       'Facility type deleted.');
           }
        }
    }

    public function destroyMany(Request $request){
        if ($request->multi_id != null){
            $facility_types = FacilityType::findOrFail($request->multi_id);
            //Make it impossible to delete this specific permission
            $msg = "";
            $count_error=0;
            $count_delete=0;
            foreach ($facility_types as $facility_type){
                $facility = Facility::where('facility_type_id', $facility_type->id)->get();
                if (sizeof($facility) != 0) {
                    if($count_error == 0){
                        $msg .= " ".$facility_type->name;
                    }
                    else{
                        $msg .= ", ".$facility_type->name;
                    }
                    $count_error++;

                }
                elseif($facility_type->id == 1 or $facility_type->id == 2){
                    if($count_error == 0){
                        $msg .= " ".$facility_type->name;
                    }
                    else{
                        $msg .= ", ".$facility_type->name;
                    }
                    $count_error++;

                }
                else{
                    $facility_type->delete();
                    $count_delete++;
                }

            }
            if($count_error != 0 && $count_delete != 0){
                return redirect()->route('facility-types.index')
                    ->with(['flash_message'=>
                        'Facility types deleted.','danger'=>'Cannot delete facility type'.$msg."."]);
            }
            else if($count_error == 0 && $count_delete != 0){
                return redirect()->route('facility-types.index')
                    ->with(['flash_message'=>
                        'Facility types deleted.']);
            }
            else if($count_error != 0 && $count_delete == 0){
                return redirect()->route('facility-types.index')
                    ->with(['danger'=>'Cannot delete facility type'.$msg.". Because it is a system default or it being used."]);
            }

        }
        else{
            return redirect()->route('facility-types.index')
                ->with('warning',
                    'Please select at least one record.');

        }

    }
}

dependencies/resources/views/facility_types/create.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-white">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li>
                        <a href="{{route('facilities.index')}}"><span class="title">Facilities</span></a>
                    </li>
                    <li class="active">
                        <a href="{{route('facility-types.index')}}">Facility Types</a>
                    </li>
                    <li>
                        <a href="{{route('services.index')}}"><span class="title">Services</span></a>
                    </li>
                    <li>
                        <a href="{{route('policy.index')}}">Policy</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-white">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="/admin/dashboard">Home</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">Settings</a></li>
                <li class="breadcrumb-item"><a href="{{route('facility-types.index')}}">Facility Types</a></li>
                <li class="breadcrumb-item active">Add Facility Type</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>ADD FACILITY TYPE

                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <div class="card card-transparent">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-12">
                        @if(Session::has('flash_message'))
                            <div class="alert alert-success" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                {!! Session('flash_message') !!}
                            </div>

                        @endif
                        @if ($errors->has('name') or $errors->has('abbreviation'))
                            <div class="alert alert-danger" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                @if($errors->has('name')){{ $errors->first('name') }}<br>@endif
                                @if($errors->has('abbreviation')){{ $errors->first('abbreviation') }}<br>@endif



                            </div>

                        @endif
                        <p class="small hint-text">* Indicates a required field.</p>
                        <form id="form-work" class="form-horizontal" role="form" autocomplete="off" action="{{route('facility-types.store')}}" method="post" novalidate="novalidate">
                            {{csrf_field()}}
                            <div class="form-group row{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">Name *</label>
                                <div class="col-md-9">
                                    <input type="text" class="form-control error" id="name" placeholder="Hotel" name="name"  value="{{old('name')}}" required="" aria-required="true" aria-invalid="true">
                                </div>
                            </div>


                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-3">
                                </div>
                                <div class="col-md-9">
                                    <a href="{{route('facility-types.index')}}" class="btn btn-hotel btn-primary-hotel">Back</a>
                                    <button class="btn btn-hotel btn-sec-hotel" type="submit">Add</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>



        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
@endsection

dependencies/resources/views/facility_types/edit.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-white">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li>
                        <a href="{{route('facilities.index')}}"><span class="title">Facilities</span></a>
                    </li>
                    <li class="active">
                        <a href="{{route('facility-types.index')}}">Facility Types</a>
                    </li>
                    <li>
                        <a href="{{route('services.index')}}"><span class="title">Services</span></a>
                    </li>
                    <li>
                        <a href="{{route('policy.index')}}">Policy</a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-white">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="/admin/dashboard">Home</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">Settings</a></li>
                <li class="breadcrumb-item"><a href="{{route('facility-types.index')}}">Facility Types</a></li>
                <li class="breadcrumb-item active">Edit {{$facility_type->name}}</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>EDIT {{$facility_type->name}}

                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <div class="card card-transparent">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-12">
                        @if(Session::has('flash_message'))
                            <div class="alert alert-success" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                {!! Session('flash_message') !!}
                            </div>

                        @endif
                        @if ($errors->has('name') or $errors->has('abbreviation'))
                            <div class="alert alert-danger" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                @if($errors->has('name')){{ $errors->first('name') }}<br>@endif
                                @if($errors->has('abbreviation')){{ $errors->first('abbreviation') }}<br>@endif



                            </div>

                        @endif
                        <p class="small hint-text">* Indicates a required field.</p>
                            {{ Form::model($facility_type, array('route' => array('facility-types.update', $facility_type->id), 'method' => 'PUT', 'id' => 'form-work', 'class' => 'form-horizontal', 'role'=>'form', 'autocomplete'=>'off','novalidate'=>'novalidate')) }}{{-- Form model binding to automatically populate our fields with permission data --}}
                            <div class="form-group row{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">Name *</label>
                                <div class="col-md-9">
                                    <input type="text" class="form-control error" id="name" placeholder="Hotel" name="name"  value="{{old('name',$facility_type->name)}}" required="" aria-required="true" aria-invalid="true">
                                </div>
                            </div>


                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-3">
                                </div>
                                <div class="col-md-9">
                                    <a href="{{route('facility-types.index')}}" class="btn btn-hotel btn-primary-hotel">Back</a>
                                    <button class="btn btn-hotel btn-sec-hotel" type="submit">Save Changes</button>
                                </div>
                            </div>
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>



        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
@endsection

dependencies/resources/views/facility_types/index.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-white">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li>
                        <a href="{{route('facilities.index')}}"><span class="title">Facilities</span></a>
                    </li>
                    <li class="active">
                        <a href="javascript:;">Facility Types</a>
                    </li>
                    <li>
                        <a href="{{route('services.index')}}"><span class="title">Services</span></a>
                    </li>
                    <li>
                        <a href="{{route('policy.index')}}">Policy</a>
                    </li>

                </ul>
           </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-white">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="/admin/dashboard">Home</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">Settings</a></li>
                <li class="breadcrumb-item active">Facility Types</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>FACILITY TYPES

                    <a href="{{route('facility-types.create')}}" class="btn btn-hotel btn-primary-hotel btn-top-page pull-right"><i class="icon-plus"></i> Add facility type</a>
                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <!-- START card -->
        <div class="card card-transparent">
            <div class="card-block">
                @if(Session::has('flash_message'))
                    <div class="alert alert-success" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('flash_message') !!}
                    </div>

                @endif
                @if(Session::has('warning'))
                    <div class="alert alert-warning" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('warning') !!}
                    </div>

                @endif
                @if(Session::has('danger'))
                    <div class="alert alert-danger" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('danger') !!}
                    </div>

                @endif
                <div class="table-responsive">
                    <div id="basicTable_wrapper" class="dataTables_wrapper no-footer">
                        <form action="{{route('facility_types_destroymany')}}" method="post">
                            {{csrf_field()}}
                            <table class="table table-hover dataTable no-footer" id="basicTable" role="grid">
                                <thead>
                                <tr role="row">
                                    <th style="width: 1%" class="sorting_desc" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1" aria-label="No.: activate to sort column ascending" aria-sort="descending">No</th>
                                    <th style="width: 83%" class="sorting" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1" aria-label="Title: activate to sort column ascending">Name</th>
                                    <th style="width: 15%" class="sorting" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1">Action</th>
                                    <th style="width:1%" class="text-center sorting_disabled" rowspan="1" colspan="1" aria-label="">
                                        <button class="btn btn-link"><i class="icon-trash"></i>
                                        </button>
                                    </th>
                                </tr>

                                </thead>
                                <tbody>
                                @if(sizeof($facility_types) != 0)
                                    @foreach ($facility_types as $facility)
                                        <tr role="row" class="odd">
                                            <td class="v-align-middle sorting_1">
                                                {{ $facility->id }}
                                            </td>
                                            <td class="v-align-middle">
                                                {{ $facility->name }}
                                            </td>
                                            <td class="v-align-middle">
                                                <a href="{{ URL::to('/admin/settings/facility-types/'.$facility->id.'/edit') }}" class="btn btn-hotel btn-edit pull-left" style="margin-right: 3px;"><i class="icon-pencil"></i></a>
                                                @if($facility->id == 1 or $facility->id == 2)
                                                    <button type="button" class="btn btn-hotel btn-delete pull-left" style="margin-right: 3px;" data-target="#deleteModal{{$facility->id}}" data-toggle="modal" disabled><i class="icon-trash"></i></button>
                                                @else
                                                    <button type="button" class="btn btn-hotel btn-delete pull-left" style="margin-right: 3px;" data-target="#deleteModal{{$facility->id}}" data-toggle="modal"><i class="icon-trash"></i></button>

                                                @endif
                                            </td>
                                            <td class="v-align-middle">
                                                <div class="checkbox text-center">
                                                    <input type="checkbox" value="{{$facility->id}}" id="checkbox{{$facility->id}}" name="multi_id[]">
                                                    <label for="checkbox{{$facility->id}}" class="no-padding no-margin"></label>
                                                </div>
                                            </td>
                                        </tr>

                                    @endforeach
                                    @else
                                    <tr><td></td><td>No facility types were found.</td><td></td><td></td></tr>
                                    @endif






                                </tbody>
                                <tfoot>
                                <tr><td></td><td></td><td style="text-align: right">with selected:</td><td><button type="button" class="btn btn-xs btn-hotel btn-delete" data-target="#deleteMany" data-toggle="modal"><i class="icon-trash"></i> Delete</button></td>
                                    <div class="modal fade fill-in disable-scroll" id="deleteMany" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header clearfix text-left">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body text-center m-t-20">
                                                    <h5>Are you sure you want to delete selected facility types ?</h5>
                                                    <button type="button" class="btn btn-hotel btn-primary-hotel" data-dismiss="modal" aria-hidden="true">Cancel</button>&nbsp;
                                                    <button class="btn btn-hotel btn-delete" type="submit">Delete</button>

                                                </div>
                                            </div>
                                            <!-- /.modal-content -->
                                        </div>
                                        <!-- /.modal-dialog -->
                                    </div>
                                </tr>



                                </tfoot>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
            <div style="text-align: center">
                {{$facility_types->links()}}
            </div>
        </div>
        <!-- END card -->

        <!-- DELETE MODAL -->
        @if(sizeof($facility_types) != 0)
            @foreach ($facility_types as $facility)
               <div class="modal fade fill-in disable-scroll" id="deleteModal{{$facility->id}}" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header clearfix text-left">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
                                        </button>
                                    </div>
                                    <div class="modal-body text-center m-t-20">
                                        <form action="{{ route('facility-types.destroy', $facility->id) }}" method="post">
                                            <input type="hidden" name="_method" value="delete" />
                                            {!! csrf_field() !!}
                                            <h5>Are you sure you want to delete {{$facility->name}}?</h5>
                                            <button type="button" class="btn btn-hotel btn-primary-hotel" data-dismiss="modal" aria-hidden="true">Cancel</button>&nbsp;
                                            <button class="btn btn-hotel btn-delete" type="submit">Delete</button>
                                        </form>

                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>

        @endforeach
    @endif


        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->

@endsection